#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : php-Molten
Version  : 0.1.2beta
Release  : 1
URL      : https://pecl.php.net//get/Molten-0.1.2beta.tgz
Source0  : https://pecl.php.net//get/Molten-0.1.2beta.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: php-Molten-lib = %{version}-%{release}
BuildRequires : buildreq-php
BuildRequires : curl-dev

%description
# molten
[![Build Status](https://travis-ci.org/chuan-yun/Molten.svg?branch=master)](https://travis-ci.org/chuan-yun/Molten)

%package lib
Summary: lib components for the php-Molten package.
Group: Libraries

%description lib
lib components for the php-Molten package.


%prep
%setup -q -n Molten-0.1.2beta

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
phpize
%configure
make  %{?_smp_mflags}

%install
%make_install


%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/extensions/no-debug-non-zts-20180731/molten.so
